// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNqBNnRpdzvt0TIE1ow6NHFH2pzgKx0ZY',
    appId: '1:334571649336:web:b3374b765f811414bee9cd',
    messagingSenderId: '334571649336',
    projectId: 'csc-4360-travel-buddy-app',
    authDomain: 'csc-4360-travel-buddy-app.firebaseapp.com',
    storageBucket: 'csc-4360-travel-buddy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxGKe5XQ5iJ4OncCz4ahEZny_rTvkqJw',
    appId: '1:334571649336:android:0827ff6c75112cf1bee9cd',
    messagingSenderId: '334571649336',
    projectId: 'csc-4360-travel-buddy-app',
    storageBucket: 'csc-4360-travel-buddy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlnmC2K-xrmlc9jE7f3bjGjW-zEuY_BpQ',
    appId: '1:334571649336:ios:33dee57b93ab1df8bee9cd',
    messagingSenderId: '334571649336',
    projectId: 'csc-4360-travel-buddy-app',
    storageBucket: 'csc-4360-travel-buddy-app.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlnmC2K-xrmlc9jE7f3bjGjW-zEuY_BpQ',
    appId: '1:334571649336:ios:33dee57b93ab1df8bee9cd',
    messagingSenderId: '334571649336',
    projectId: 'csc-4360-travel-buddy-app',
    storageBucket: 'csc-4360-travel-buddy-app.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNqBNnRpdzvt0TIE1ow6NHFH2pzgKx0ZY',
    appId: '1:334571649336:web:b122b2fa9703aab7bee9cd',
    messagingSenderId: '334571649336',
    projectId: 'csc-4360-travel-buddy-app',
    authDomain: 'csc-4360-travel-buddy-app.firebaseapp.com',
    storageBucket: 'csc-4360-travel-buddy-app.firebasestorage.app',
  );
}
